name: ubuntu-gnu

permissions:
  actions: write

on:
  push:
    branches:
      - dev
      - luis
      
  pull_request:
    branches:
      - main
      - dev

jobs:
  
  builds-and-test:
    runs-on: ubuntu-latest
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11

    - name: Builds mfem-geg
      run: | 
        cmake -S external/mfem-geg -B mfem-geg-build/ -DCMAKE_BUILD_TYPE=Release
        cmake --build mfem-geg-build/
        cmake --install mfem-geg-build/ --prefix mfem-geg-install/
  
    - name: Builds semba/dgtd
      uses: lukka/run-cmake@v10
      env: 
        MFEM_DIR: 'mfem-geg-install/lib/cmake/mfem/'
      with:
        configurePreset: 'gnu'
        buildPreset: 'gnu'
        buildPresetAdditionalArgs: "['--parallel']"
      
    - name: Run unit tests 
      run: |
        build/gnu/bin/hesthavenComparison_tests
        build/gnu/bin/mfem_tests
        build/gnu/bin/adapter_tests

    - name: Run system tests 
      run: |
        build/gnu/bin/maxwell_tests
        build/gnu/bin/rcs_tests


      
