name: ubuntu-gnu

on:    
  pull_request:
    branches:
      - main
      - dev

jobs:
  
  builds-and-test:
    runs-on: ubuntu-latest
    
    steps:       
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    # - name: Builds mfem-geg
    #   run: | 
    #     cmake -S external/mfem-geg \
    #           -B mfem-geg-build/ \
    #           -DCMAKE_BUILD_TYPE=Release \
    #           -DCMAKE_INSTALL_PREFIX=mfem-geg-install \
    #           -G Ninja
    #     cmake --build mfem-geg-build/ -j
    #     cmake --install mfem-geg-build/

    - name: Builds semba/dgtd
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'gnu'
        buildPreset: 'gnu'
        buildPresetAdditionalArgs: "['--parallel']"

    - name: Run hesthavenComparison tests 
      run: build/gnu/bin/hesthavenComparison_tests

    - name: Run mfem tests 
      run: build/gnu/bin/mfem_tests

    - name: Run maxwell tests 
      run: build/gnu/bin/maxwell_tests

    - name: Run maxwell solver tests
      run: build/gnu/bin/maxwell_solver_tests

    - name: Run maxwell cases tests
      run: build/gnu/bin/cases_tests

    # - name: Run system tests 
    #   run: |
    #     build/gnu/bin/rcs_tests


      
