name: windows-msvc

permissions:
  actions: write

on:
  pull_request:
    branches:
      - main
      - dev
   
jobs:
  builds-and-tests:
    
    runs-on: windows-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: getcmake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master

    # - name: Builds mfem-geg
    #   run: | 
    #     cmake -S external/mfem-geg -B mfem-geg-build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=mfem-geg-install -G Ninja
    #     cmake --build mfem-geg-build/ -j --config Release
    #     cmake --install mfem-geg-build/ --config Release
        
    - name: Builds semba/dgtd
      uses: lukka/run-cmake@v10
      env: 
        MFEM_DIR: 'mfem-geg-install/lib/cmake/mfem/'
      with:
        configurePreset: 'x64-Release'
        buildPreset: 'x64-Release'
        buildPresetAdditionalArgs: "['--parallel', '--verbose']"

    - name: Verify test files exist
      run: dir build/x64-Release/bin/Release

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      
    - name: Run maxwell mfem tests 
      run: build/x64-Release/bin/Release/mfem_tests.exe

    - name: Run hesthaven comparison tests 
      run: build/x64-Release/bin/Release/hesthavenComparison_tests.exe

    - name: Run maxwell tests 
      run: build/x64-Release/bin/Release/maxwell_tests.exe

    - name: Run maxwell solver tests 
      run: build/x64-Release/bin/Release/maxwell_solver_tests.exe

    - name: Run cases tests 
      run: build/x64-Release/bin/Release/cases_tests.exe

    # - name: Run system tests 
    #   run: |
    #     build/gnu/bin/rcs_tests


        
    
